@startuml Block

!include BlockId.pu
!include BlockPos.pu
!include BlockOpacity.pu
!include BlockMaterial.pu
!include BlockLightLevel.pu

class Block {
    blockId: BlockId
    name: string
    hardness: number
    resistance: number
    position: BlockPos
    opacity: BlockOpacity
    material: BlockMaterial
    lightLevel: BlockLightLevel
}

Block *-down- BlockId
Block *-down- BlockPos
Block *-down- BlockOpacity
Block *-down- BlockMaterial
Block *-down- BlockLightLevel

@enduml
